name: ðŸ§ Config contents
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        description: 'The target environment to deploy to'
    secrets:
      encodedContent:
        required: true
        description: 'Encoded json file. An equivalent "config_template" must exist at the root of the repository'
jobs:
  validate-config:
    runs-on: macos-latest
    environment: ${{ inputs.target }}
    env:
      ENCODED_CONTENT: ${{ secrets.encodedContent }}
    steps:
      - name: setup-repo
        uses: actions/checkout@v4

      - name: get-scripts
        uses: actions/checkout@v4
        with:
          repository: Juliotati/juliotati_app
          ssh-strict: false
          sparse-checkout: scripts/
          path: scripts/

      - name: verify-config-existence-and-contents
        run: |
          echo $ENCODED_CONTENT | base64 --decode > config.json
          chmod +x "${GITHUB_WORKSPACE}/scripts/all_functions.sh"
          chmod +x "${GITHUB_WORKSPACE}/scripts/verify_config_contents.sh"
          bash "${GITHUB_WORKSPACE}/scripts/verify_config_contents.sh"
